node_id: 0318edaf-4a08-49c9-ba03-c4d732fd8d9c
owner: OWNER
business: BUSINESS
deploy_location: SEATTLE

# dictionary of public transmission flags (BitCoin, LiteCoin, etc...)
public_transmission: 
    p1_pub_trans: off
    p2_pub_trans: off
    p3_pub_trans: off
    p4_pub_trans: off

# host:port:id:phases
# phase 1 = 00001
# phase 2 = 00011 ...
peers:
    - localhost:8081:8f0aabca-aa2e-4aab-a1d2-8420ffba0cce:00010
    - localhost:8082:64110e10-cdf9-41e5-a13a-f95ba1f5acdb:00011
    - localhost:8083:7475ab41-58d9-49f6-b3be-f207fc96bb51:00010
    - localhost:8084:4cc5d599-df17-4c4a-8f3c-2ce70f874c54:00010 #change when node 5 imported